### ISSUE TITLE
[BACKEND] Onboarding 2 - Saving a User's Top 3 Playlists

### ISSUE THREAD

**Issue by nehalgarg03** [sheldor1510/spotifynder#12]
Note: I forgot to put a # in front of all my commits for the tag so please scroll down to see all my commits for this issue in a comment below. I also attached them here:

Commits: 98c0225302cefc669a505de8fd6e3cfbb746efcd. 044c556152694c1f4f3ac7ca7e97ded59e31c103

Description: A user will choose three of their top personal playlists. Then these playlists will be saved in a user's object.

Owner: Nehal 

Feature Weight: 3 points

Tag: #12

Expected Outcome: User should be able to select their top three playlists from the data fetched from the spotify api. This information will then be stored in the database.

**Comment by aanyamehta1** [comment]
This is great! How will you handle when a user has fewer than 3 playlists available. Consider adding a fallback or validation in the selection process.

**Comment by nehalgarg03** [comment]
The commits for this issue:

044c556152694c1f4f3ac7ca7e97ded59e31c103 98c0225302cefc669a505de8fd6e3cfbb746efcd

**Comment by nehalgarg03** [comment]
Resolved and implemented!
