### ISSUE TITLE
[BACKEND] Onboarding 2 - Personality Prompts

### ISSUE THREAD

**Issue by nehalgarg03** [sheldor1510/spotifynder#13]
Note: I forgot to put a # in front of all my commits for the tag so please scroll down to see all my commits for this issue in a comment below. I also attached them here:

Commits: b2df536e9af7e71e5333c635c515f9faefdb2470.  70c9aa1f269a8332769ce96ba9c4c420e71d9196

Description: A user will fill out the personality prompts and that information will be stored in the database in the user's object.

Owner: Nehal

Feature Weight: 2 points

Tag: #13

Expected Outcome: Should be able to see the user's answers to the personality prompts in the database for their user object.

**Comment by nandapriyal2003** [comment]
This is a valuable feature! Ensure the personality prompts are validated before saving and consider structuring the data in a flexible format to allow for future updates or additional prompts without schema changes.

**Comment by nehalgarg03** [comment]
Here are my commits for this issue: 

70c9aa1f269a8332769ce96ba9c4c420e71d9196. b2df536e9af7e71e5333c635c515f9faefdb2470

**Comment by nehalgarg03** [comment]
Implemented and finished! Is working as it should!
