### ISSUE TITLE
[BACKEND ] Onboarding 2 - Get User Personal Playlists

### ISSUE THREAD

**Issue by nehalgarg03** [sheldor1510/spotifynder#14]
Note: I forgot to put a # in front of all my commits for the tag so please scroll down to see all my commits for this issue in a comment below. I also attached them here:

Commits: 98c0225302cefc669a505de8fd6e3cfbb746efcd.   72e41350bcb9220f7cf140539802983632a3c76c

Description: Using Spotify API's I will grab a user's personal playlists (using their saved user token) and display them on the screen.

Owner: Nehal

Tag: #14

Expected Outcome: A drop down/display of a user's playlists directly from their spotify account. 

Feature Weight: 5 points

**Comment by nandapriyal2003** [comment]
This is an excellent feature! Ensure proper error handling for expired or invalid tokens when interacting with the Spotify API

**Comment by sheldor1510** [comment]
Spotify's API returns playlists in paginated form. Will the implementation include logic to fetch all playlists if the user has more than the API's limit per request (e.g., 50 playlists)?

**Comment by nehalgarg03** [comment]
The commits for this issue: 

72e41350bcb9220f7cf140539802983632a3c76c

98c0225302cefc669a505de8fd6e3cfbb746efcd

**Comment by agunjikar** [comment]
Cool! What happens if a user has no personal playlists? Will they get to select albums/will a default one display?

**Comment by nehalgarg03** [comment]
Works as intended!
