### ISSUE TITLE
[BACKEND] Discovery Page - Implement Accept Button

### ISSUE THREAD

**Issue by sheldor1510** [sheldor1510/spotifynder#15]
**Description**: Whenever a user swipes right on a profile, we want it to create an object in the matches table with `status: pending` and the `requestor` property being the user who's currently logged in and the `user_requested` property being the user on whom the right swipe was made.

**Owner**: Anshul

**Expected Outcome**: The user who got right swiped on can see the request in their Chats page and decide to accept or reject.

**Points**: 3 Points (Medium Feature)

**Comment by tanushsavadi** [comment]
This is clear and well-defined! The flow for creating a match object seems straightforward. Great job, looking forward to seeing the outcome! 🚀

**Comment by sheldor1510** [comment]
Closing the issue as backend endpoints were made and frontend integration coded and tested!
