### ISSUE TITLE
[BACKEND] Discovery Page - Implement Reject Button

### ISSUE THREAD

**Issue by sheldor1510** [sheldor1510/spotifynder#16]
**Description**: Whenever a user swipes left on a profile, we want it to add it to the user's `rejected_pile` property so the user is not shown that profile again when exploring new profiles.

**Owner**: Anshul

**Expected Outcome**: The user who got left swiped does not show up on the user's discovery page.

**Points**: 3 Points (Medium Feature)

**Comment by nandapriyal2003** [comment]
This is a great feature! Ensure the rejected_pile is optimized for scalability to handle a growing number of rejected profiles efficiently and consider edge cases like profile updates or removals to maintain a seamless user experience.

**Comment by nehalgarg03** [comment]
Great work! Define behavior for edge cases, such as when a profile already exists in the rejected_pile. This could help prevent redundant updates.

**Comment by sheldor1510** [comment]
Closing the issue as backend endpoints were made and frontend integration coded and tested!
