### ISSUE TITLE
[BACKEND] Onboarding-1:  Set Up Spotify OAuth Callback Backend Route

### ISSUE THREAD

**Issue by nandapriyal2003** [sheldor1510/spotifynder#17]
- Implement a backend route to handle Spotify's OAuth callback. Retrieve the authorization code, exchange it for an access token using Spotify's API, and handle potential errors (e.g., invalid or expired token).
- Tag: #45 
- Size Category: medium, 3 points
- Owner: Priyal Nanda
- Expected Outcome: Backend route successfully retrieves and validates access tokens from Spotify.

**Comment by sheldor1510** [comment]
Since this involves sensitive user data, are there any plans to encrypt the token or implement additional security measures to protect it during storage and transmission?
