### ISSUE TITLE
[BACKEND] Chat Feature - implement chats table and matching

### ISSUE THREAD

**Issue by satvinaik-umass** [sheldor1510/spotifynder#20]
Description: Create a Chat table with the following schema (3pts- medium feature): 

- id (Primary Key)
- match_id (Foreign Key referencing Match table)
- conversation_history (JSON or text field to store messages)

Ensures that the Chat table is linked to matches with "status: accepted." Populate the table so that all matches for which the user is either the requestor or user_requested appear in the chats section.

Owner: Satvi Naik
Expected Outcome: A functional database schema for storing chat data, with all matches for the logged-in user displayed in the users section next to the chat.

**Comment by nehalgarg03** [comment]
If sensitive data is involved, clarify how access control will be handled to ensure only authorized users can view or manipulate their chat data.

**Comment by tanushsavadi** [comment]
This looks solid! The schema and linking with the "status: accepted" matches are well-thought-out. Great job ensuring seamless integration with the chat section. 🚀 Let me know if you need help with testing or anything else!
