### ISSUE TITLE
[BACKEND] Onboarding-1: Store Access Token and User Data in Database

### ISSUE THREAD

**Issue by nandapriyal2003** [sheldor1510/spotifynder#22]
- Description: Extend the database schema to store user data and Spotify access tokens. Implement logic to securely save and retrieve this information after successful authentication. Ensure token encryption or secure storage practices.
- Tag: #45 
- Size Category: Small 2 points
- Owner: Priyal Nanda
- Expected Outcome: User and access token data securely stored in the database and linked to the user profile.

**Comment by tanushsavadi** [comment]
This looks great! One suggestion would be to clearly define the encryption standard or library for token security, ensuring consistent implementation across the application. We did discuss this but just ensure you explicitly mention it too!
