### ISSUE TITLE
[BACKEND] Chats Page - Implement Accept/Reject button functionality

### ISSUE THREAD

**Issue by sheldor1510** [sheldor1510/spotifynder#23]
**Description**: If a user likes a profile of the requests they see, they should be able to accept it. Once they accept, that particular object in the matches table should have its `status`property changed from `pending` to `accepted`. If the user rejects it, it should change to `rejected`.

**Owner**: Anshul

**Expected Outcome**: The user can accept the requests they see to start chatting with them or reject the request.

**Points**: 3 Points (Medium Feature)

**Comment by tanushsavadi** [comment]
This looks solid! A small suggestion would be to ensure error handling for cases where the match object is not found or when there's a database update issue. This would help maintain a smooth user experience. I can help you with testing this if necessary!

**Comment by sheldor1510** [comment]
Closing the issue as backend endpoints were made and frontend integration coded and tested!
