### ISSUE TITLE
[BACKEND] Onboarding-1: Setup Backend Spotify authentication

### ISSUE THREAD

**Issue by nandapriyal2003** [sheldor1510/spotifynder#24]
- Description: Integrate Spotify authentication into the backend. Make an account on the spotify for developers, create a dashboard for our app and then Set up the logic to handle Spotify authentication by making API requests to Spotify’s authorization endpoint, allowing users to log in with their credentials. Once the user is authenticated, the backend processes the callback from Spotify to extract the authorization code. This code is then exchanged for a user token, which is used to authenticate future API calls to Spotify. 
- Tag: #45 , Commit # 34ce071 and f8c1880
- Owner: Priyal Nanda
- Expected Outcome: The goal of integrating Spotify authentication and fetching the Spotify API in the app is to enable personalized user experiences based on their Spotify data.

**Comment by nehalgarg03** [comment]
Great to see error handling mentioned for expired tokens. Consider also specifying what should happen if the token verification call fails due to network issues or other unexpected errors.

**Comment by tanushsavadi** [comment]
Looks great! Maybe specify how periodic validation will work (e.g., intervals or triggered by specific events) for added clarity. 🚀
