### ISSUE TITLE
[BACKEND] Discovery Page - Set Up Database Schema for User Profiles

### ISSUE THREAD

**Issue by tanushsavadi** [sheldor1510/spotifynder#25]
Description: Create a Sequelize model for UserProfile with attributes: id, username, topArtists, topTracks, topPlaylists, compatibilityScore.

Tag: #25

Owner: Tanush Savadi

Expected Outcome: A functioning SQLite database table for user profiles.

**Comment by nehalgarg03** [comment]
In addition to creating a functioning SQLite table, consider including sample data or queries to validate the implementation and confirm it works as expected.

**Comment by tanushsavadi** [comment]
Closing this issue (issue: https://github.com/sheldor1510/spotifynder/issues/25) after testing the backend endpoints and also the frontend integration with it.
