### ISSUE TITLE
[BACKEND] Onboarding-1: Set Up College List

### ISSUE THREAD

**Issue by nandapriyal2003** [sheldor1510/spotifynder#26]
- Description: Create a backend API endpoint or find a list of colleges. Fetch the list from an external or internal source and provide it as a JSON response.
- Tag: 
- Size Category: Small 1 point
- Owner: Priyal Nanda
- Expected Outcome: delivers a formatted college list for frontend use in json format.

**Comment by sheldor1510** [comment]
Have you considered whether combining fetching and saving functionality into a single endpoint could impact scalability or code maintainability? It might be worth separating these concerns to ensure clarity and better error handling.
