### ISSUE TITLE
[BACKEND] Discovery Page - Set Up Express Route to Fetch User Profiles

### ISSUE THREAD

**Issue by tanushsavadi** [sheldor1510/spotifynder#27]
Description: Implement a GET /discovery route in ExpressJS to fetch user profiles based on filter parameters (artists, tracks, playlists, compatibility).

Tag: #27

Owner: Tanush Savadi

Expected Outcome: A functional endpoint that queries the database based on provided filters.

**Comment by nandapriyal2003** [comment]
This is a great feature! Ensure the filters are well-validated to avoid invalid queries.

**Comment by tanushsavadi** [comment]
Closing this issue (issue: https://github.com/sheldor1510/spotifynder/issues/27) after testing the backend endpoints and also the frontend integration with it.
