### ISSUE TITLE
[BACKEND] Onboarding-1: Implement College Selection json file

### ISSUE THREAD

**Issue by nandapriyal2003** [sheldor1510/spotifynder#28]
- Description: Develop a single backend call that supports fetching a list of colleges and saving the selected college. 
      - Fetch Colleges: Retrieve a list of colleges from an external or internal source and provide it as a JSON response. 
      -   Save Selected College: Accept the selected or manually entered college from the frontend, validate the input, and store it in the local database on user’s end.
- Tag:  #60 
Size Category: Medium 3 points
- Owner: Priyal Nanda
- Expected Outcome: fetching a list of colleges and saving the user’s selected college from the provided dropdown

**Comment by tanushsavadi** [comment]
This looks solid! You might want to clarify if the list of colleges will support pagination or search functionality for scalability which would be good to have!
