### ISSUE TITLE
[BACKEND] Chat Feature: Fetch Conversation History for Chats

### ISSUE THREAD

**Issue by satvinaik-umass** [sheldor1510/spotifynder#30]
Description: Fetches conversation history from the Chat table. Use the match_id as the key to retrieve the correct chat object. Display the fetched messages in the chat interface when a user clicks a chat bubble. (3pts - medium feature)
Tag: #65 
Owner: Satvi Naik
Expected Outcome: Clicking on a user name retrieves and displays the complete conversation history associated with the corresponding match_id.

**Comment by nehalgarg03** [comment]
Specify how to handle scenarios where no chat history exists for a given match_id.

**Comment by tanushsavadi** [comment]
This is a well-defined issue! Fetching conversation history using `match_id` ensures proper data retrieval and seamless integration with the chat interface. Looks good to go! Let me know if there's anything specific you'd like help testing.
