### ISSUE TITLE
[BACKEND] Chat Feature: Update Conversation History

### ISSUE THREAD

**Issue by satvinaik-umass** [sheldor1510/spotifynder#31]
Description: Enable real-time updates to the conversation_history in the Chat table. When a user sends a new message:
Fetch the relevant Chat object using match_id.
Append the new message to the conversation_history.
Save the updated object back to the database.

Owner: Satvi Naik
Expected Outcome: Messages sent by users are appended to the correct chat, and the updates are reflected in the chat interface.

**Comment by sheldor1510** [comment]
What happens if the Chat object is not found or if saving the updated object fails? Providing clear error messages and fallback behavior can improve the user experience.
