### ISSUE TITLE
[BACKEND] Filter Section - Fetch Filter Options and Integrate with Profile Queries

### ISSUE THREAD

**Issue by tanushsavadi** [sheldor1510/spotifynder#34]
Description:
- Use Sequelize to dynamically query filter options (artists, tracks, playlists) from the database.
- Modify the GET /discovery route to update results dynamically based on selected filter parameters from the frontend.

Tag: #34

Owner: Tanush Savadi

Expected Outcome: Filters dynamically affect profile results, and filter options are fetched from the database.

**Comment by nandapriyal2003** [comment]
Great feature! Ensure queries are optimized for performance and validate filter parameters to avoid issues with invalid inputs.

**Comment by tanushsavadi** [comment]
Closing this issue (issue: https://github.com/sheldor1510/spotifynder/issues/67) after testing the backend endpoints and also the frontend integration with it.

**Comment by tanushsavadi** [comment]
Closing this issue (issue: https://github.com/sheldor1510/spotifynder/issues/34) after testing the backend endpoints and also the frontend integration with it.
