### ISSUE TITLE
[BACKEND]: Onboarding 1-Selection of Top Artists and Tracks

### ISSUE THREAD

**Issue by agunjikar** [sheldor1510/spotifynder#35]
Description: Must fetch the top artists and top tracks using the users saved Spotify token.
Tag: 
Size Category: Medium 3 points
Tag: #35
Owner: Avni Gunjikar
Expected Outcome: The top artists and tracks will then be displayed in the UI 
PR Tag: #47

**Comment by aanyamehta1** [comment]
This looks good! Ensure you add error handling to verify token is valid and also display error message to UI for feedback when API calls fail. Consider edge cases of users with no top artists/no data available
