### ISSUE TITLE
[BACKEND]: Onboarding 1- Selection of Top Tracks and Artists 

### ISSUE THREAD

**Issue by agunjikar** [sheldor1510/spotifynder#36]
Description: The user selects their Top 3 artists and songs from their top artists and songs.
Tag: 
Size Category: Medium (3pts)
Owner: Avni Gunjikar
Expected Outcome: The users top artists and tracks will be displayed on their profile and then this is stored in the database in our users object.

**Comment by aanyamehta1** [comment]
This is a well-defined issue but consider handling a case where user does not have sufficient data to display artists, tracks. Will there be placeholder data or default message?
