### ISSUE TITLE
[BACKEND]: Discovery Page - Filters - Reset Button 

### ISSUE THREAD

**Issue by agunjikar** [sheldor1510/spotifynder#37]
Description: The reset button will make the the filters go to default values.
Tag:
Size Category: Medium 3 points
Owner: Avni Gunjikar
Expected Outcome: The values will be reset to the default values and this will reflect in the UI.

**Comment by satvinaik-umass** [comment]
Great job! In addition to this, adding a confirmation prompt before resetting the filters would avoid accidental resets by the user which can be useful so nothing gets accidentally deleted.
