### ISSUE TITLE
[BACKEND]: Discovery Page - Filter Page - I'm Feeling Lucky Button

### ISSUE THREAD

**Issue by agunjikar** [sheldor1510/spotifynder#38]
Description: Implements the I'm Feeling Lucky Button (essentially the randomize button).
Tag:
Size Category: Medium 3 points
Owner: Avni Gunjikar
Expected Outcome: The filter values will be randomized and then this will reflect in the front end and will be stored to the database.

**Comment by aanyamehta1** [comment]
This looks great! It seems like you've incorporated UI feedback when the button is clicked, which will be reflected in the front-end.
