### ISSUE TITLE
[BACKEND]: Profile Page - Fetch User Information

### ISSUE THREAD

**Issue by aanyamehta1** [sheldor1510/spotifynder#39]
**Description:** 
Create a GET API endpoint to fetch the user's `email` and `spotifyId` from the users table with Sequelize. Authenticate the user using with the `access_token` and return the data to display on profile page.

**Owner:** Aanya

**Expected Outcome:** The user can view their email and spotifyId on their profile page, which is dynamically displayed.

Points: 2 Points (Small Feature)

**Comment by satvinaik-umass** [comment]
Consider adding error handling to notify the user if their email or spotifyId is unavailable in the database because sometimes they might accidentally use a id that is not in the database

**Comment by aanyamehta1** [comment]
Closing issue, fetched user information successfully and displayed this on profile feature.
