### ISSUE TITLE
[BACKEND] Profile Page - Fetch Top Tracks from Database

### ISSUE THREAD

**Issue by aanyamehta1** [sheldor1510/spotifynder#40]
**Description:**
Create a GET API endpoint to fetch the user's `topTracks` from the `users` table with Sequelize. Authenticate the user using with the `access_token` and return the images of tracks to display on profile page.

**Owner:** Aanya

**Expected Outcome:** The user can view the images of their top 3 tracks, dynamically displayed on the profile page.

**Points:** 2 Points (Small Feature)

**Comment by agunjikar** [comment]
Cool feature! Making use of the previous fetching of the top tracks. Make sure there re no troubles with authentication!

**Comment by tanushsavadi** [comment]
I like the implementation that you have proposed here, good work on this fetch operation.

**Comment by aanyamehta1** [comment]
Closing issue, finished integrating backend to display all track images to frontend. No troubles with authentication, able to fetch from spotify API successfully.
