### ISSUE TITLE
[BACKEND] Profile Page - Fetch Artists from Database

### ISSUE THREAD

**Issue by aanyamehta1** [sheldor1510/spotifynder#41]
**Description:**
Create a GET API endpoint to fetch the user's `topArtists` from the `users` table with Sequelize. Authenticate the user using with the `access_token` and return the images of artists to display on profile page.

**Owner:** Aanya

**Expected Outcome:** The user can view the images of their top 3 artists, dynamically displayed on the profile page.

**Points:** 2 Points (Small Feature)

**Comment by satvinaik-umass** [comment]
This is great,  but consider limiting the number of artists returned in the response (e.g., the top 3 as specified) to improve performance and reduce unnecessary data transfer.

**Comment by agunjikar** [comment]
Cool, will the users be able to change the order of their top artists?

**Comment by aanyamehta1** [comment]
Closing issue, finished integrating backend to display all artist images from data fetched to frontend. Works and ensured to have a limit of 3.
