### ISSUE TITLE
[BACKEND] Profile Page - Fetch Playlists from Database

### ISSUE THREAD

**Issue by aanyamehta1** [sheldor1510/spotifynder#42]
**Description:**
Create a GET API endpoint to fetch the user's `topPlaylists` from the `users` table with Sequelize. Authenticate the user using with the `access_token` and return the images of playlists to display on profile page.  Appropriate error handling will be considered, such as cases when user does not have any playlists or when the database query fails. The endpoint will also use a `limit` parameter to ensure only the top 3 playlists are retrieved. 

**Owner:** Aanya

**Expected Outcome:** The user can view the images of their top 3 playlists, dynamically displayed on the profile page. 

**Points:** 2 Points (Small Feature)

**Comment by satvinaik-umass** [comment]
I think including pagination or a limit parameter in case the user’s topPlaylists list grows beyond 3 in the future would be good so the list does not get too large.

**Comment by aanyamehta1** [comment]
done, added that!

**Comment by aanyamehta1** [comment]
Closing issue, finished integrating backend to display all playlist images from data fetched to frontend. Works and ensured to have a limit of 3.
