### ISSUE TITLE
[BACKEND] Profile Page - Fetch Personality Prompts from Database

### ISSUE THREAD

**Issue by aanyamehta1** [sheldor1510/spotifynder#43]
**Description:**
Create a GET API endpoint to fetch the user's `personalityPrompts` from the `users` table with Sequelize. Authenticate the user using with the `access_token` and return `prompts` to display on profile page. This was initialized in the onboarding feature.

**Owner:** Aanya

**Expected Outcome:** The user can view their personality prompt responses, dynamically displayed on the profile page.

**Points:** 2 Points (Small Feature)

**Comment by agunjikar** [comment]
This is nice, what about the custom personality prompts?

**Comment by aanyamehta1** [comment]
Finished integrating backend to display all personality prompts from data fetched to frontend. Users can edit and change them and will update in Sequelite. Considered error handling and comments by teammates.
