### ISSUE TITLE
[BACKEND] Profile Page: Update Personality Prompts 

### ISSUE THREAD

**Issue by aanyamehta1** [sheldor1510/spotifynder#44]
**Description:** Create a POST API endpoint to update the user's `personalityPrompts` in the users table using Sequelize. Authenticate the `user` with the `access_token` and accept an updated `personalityPrompts` array from the request body. Validate the inputs via error handling of invalid inputs and limiting length of inputs and save the updated prompts in the database. The feature will support updates triggered by a form submission on the frontend.

**Owner:** Aanya

**Expected Outcome:** The user can update their `personalityPrompts` from the frontend form, and the new prompts will be stored in the database and reflected dynamically on their profile page.

**Points:** 2 Points (Small Feature)

**Comment by satvinaik-umass** [comment]
This looks great but I think adding validation to ensure the prompts meet format or length requirements would ensure proper requirements are met.

**Comment by aanyamehta1** [comment]
Closing this issue after testing the API endpoints and frontend integration. Shows on profile and updates in sequelite database, included error handling as well.
